---
dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
env:
  - RAILS_VERSION="~> 4.2.11"
  - RAILS_VERSION="~> 5.2.4"
  - RAILS_VERSION="~> 6.0.2"
jobs:
  exclude:
    - rvm: 2.4.9
      env: RAILS_VERSION="~> 6.0.2"

before_install: gem install bundler -v 1.17.3
before_script:
  - ".ci/install_rabbitmq"
bundler_args: --jobs 3 --retry 3
